basePath: /api/v1
definitions:
  api.ErrorEnvelope:
    properties:
      error:
        $ref: '#/definitions/httpclient.HTTPError'
    required:
    - error
    type: object
  health_check.HealthCheckModel:
    properties:
      status:
        type: string
      system_info:
        $ref: '#/definitions/health_check.SystemInfo'
    required:
    - status
    - system_info
    type: object
  health_check.SystemInfo:
    properties:
      version:
        type: string
    required:
    - version
    type: object
  httpclient.HTTPError:
    properties:
      code:
        type: string
      message:
        type: string
    required:
    - code
    - message
    type: object
host: localhost:4000
info:
  contact: {}
  description: REST API for Model Registry BFF
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  title: Model Registry BFF REST API
  version: 1.0.0
paths:
  /healthcheck:
    get:
      description: Provides a healthcheck response indicating the status of key services.
      operationId: getHealthcheck
      produces:
      - application/json
      responses:
        "200":
          description: Successful healthcheck response
          schema:
            $ref: '#/definitions/health_check.HealthCheckModel'
        "401":
          description: Unauthorized. Authentication is required.
          schema:
            $ref: '#/definitions/api.ErrorEnvelope'
        "403":
          description: Forbidden. User does not have permission to access the resource.
          schema:
            $ref: '#/definitions/api.ErrorEnvelope'
        "404":
          description: Not Found. Resource does not exist.
          schema:
            $ref: '#/definitions/api.ErrorEnvelope'
        "422":
          description: Unprocessable Entity. Validation error.
          schema:
            $ref: '#/definitions/api.ErrorEnvelope'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ErrorEnvelope'
      summary: Returns the health status of the application
      tags:
      - healthcheck
schemes:
- http
- https
swagger: "2.0"
