model_catalogs:
  - name: "Organization AI Models"
    id: organization_ai_models
    type: yaml
    enabled: true
    properties:
      yamlCatalogPath: dev-organization-models.yaml
    labels:
      - Organization AI
  - name: "Validated AI Models"
    id: validated_ai_models
    type: yaml
    enabled: true
    properties:
      yamlCatalogPath: dev-validated-models.yaml
    labels:
      - Validated AI
  - name: "Community and Custom Models"
    id: community_custom_models
    type: yaml
    enabled: true
    properties:
      yamlCatalogPath: dev-community-models.yaml

mcp_catalogs:
  - name: "Organization MCP Servers"
    id: organization_mcp_servers
    type: yaml
    enabled: true
    properties:
      yamlCatalogPath: dev-organization-mcp-servers.yaml
    labels:
      - Organization MCP
  - name: "Community and Custom MCP Servers"
    id: community_mcp_servers
    type: yaml
    enabled: true
    properties:
      yamlCatalogPath: dev-community-mcp-servers.yaml
