catalogs:
  - name: "Hugging Face Hub"
    id: "huggingFace"
    type: hf
    enabled: true
    includedModels: 
      - "meta-llama/Llama-3.2-1B"
      - "microsoft/Phi-3-mini-4k-instruct"
      - "Anwarkh1/Skin_Cancer-Image_Classification"
    excludedModels:
      - "Granite/*"
    properties:
      syncInterval: "24h"