name: Test UI container image build and deployment
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "clients/ui/**"
      - ".github/workflows/**"
      - "!LICENSE*"
      - "!DOCKERFILE*"
      - "!**.gitignore"
      - "!**.md"
      - "!**.txt"

permissions: # set contents: read at top-level, per OpenSSF ScoreCard rule TokenPermissionsID
  contents: read

env:
  IMG_ORG: kubeflow
  IMG_REPO: model-registry-ui
  PUSH_IMAGE: false
  BRANCH: ${{ github.base_ref }}
jobs:
  build-image:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    steps:
      # checkout branch
      - uses: actions/checkout@v5
      - name: Build UI Image
        shell: bash
        run: ./scripts/build_deploy.sh
