name: Validate OpenAPI spec
on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "api/openapi/**"
      - "catalog/plugins/*/api/openapi/**"
      - "scripts/merge_openapi.sh"
      - "scripts/merge_catalog_specs.sh"

permissions: # set contents: read at top-level, per OpenSSF ScoreCard rule TokenPermissionsID
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Validate OpenAPI spec
        run: |
          make openapi/validate
